src/blog/urls.py
from django.conf.urls import url
from .views import ArticleListView, ArticleDetailView, CategoryListView
urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='article-list'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-detail'),
    url(r'^/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='category-list'),
]

src/blog_cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
]

# For development django search for static files in static_files folder (not need to collect static every time)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/articles/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from unidecode import unidecode
from django.utils.translation import ugettext_lazy as _


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Article(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False, unique=True, verbose_name=_("title"))
    short_description = models.CharField(max_length=500, null=True, blank=True, verbose_name=_("short description"))
    description = models.TextField(null=True, blank=True, verbose_name=_("description"))
    author = models.ForeignKey(AUTH_USER_MODEL, verbose_name=_("author"))
    published = models.BooleanField(default=False, verbose_name=_("published"))
    slug = models.SlugField(unique=True, null=False, blank=True)

    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name=_("updated"))
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name=_("created"))

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title', 'author']
        verbose_name = _("article")
        verbose_name_plural = _("articles")

src/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from unidecode import unidecode
from django.utils.translation import ugettext_lazy as _
from thumbnailfield.fields import ThumbnailField
import datetime
from django.contrib.auth.models import User

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Article(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False, unique=True, verbose_name=_("title"))
    category = models.ForeignKey('Category', null=True, blank=True, verbose_name=_("category"))
    short_description = models.CharField(max_length=500, null=True, blank=True, verbose_name=_("short description"))
    description = models.TextField(null=True, blank=True, verbose_name=_("description"))
    author = models.ForeignKey(AUTH_USER_MODEL, default='auth.User', verbose_name=_("author"))
    published = models.BooleanField(default=False, verbose_name=_("published"))
    img = ThumbnailField(_('thumbnail'), upload_to='img/articles', null=True, blank=True,
        pil_save_options={
            'quality': 100,
        },
        patterns={
            None: (800, 400, 'resize'),
            'large': ((640, 480, 'resize'),),
            'small': (300, 300, 'resize'),
            'tiny': (160, 120),
        })
    slug = models.SlugField(unique=True, null=False, blank=True)

    date_published = models.DateTimeField(null=True, blank=True, verbose_name=_("publication date"))
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name=_("updated"))
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name=_("created"))

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.published:
            self.date_published = datetime.datetime.now()
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['date_published', 'title']
        verbose_name = _("article")
        verbose_name_plural = _("articles")


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"), unique=True)
    parent = models.ForeignKey('Category', blank=True, null=True, verbose_name=_("parent"))
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name=_("description"))
    slug = models.SlugField(unique=True, null=False, blank=False)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name = _("category")
        verbose_name_plural = _("categories")

class UserAbout(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()

src/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Article, Category


class ArticleListView(ListView):
    context_object_name = "articles"
    model = Article
    template_name = "article_list.html"


class ArticleDetailView(DetailView):
    content_object_name = "article"
    model = Article
    template_name = "article_detail.html"

class CategoryListView(ListView):
    context_object_name = "category"
    model = Category
    template_name = "category_list.html"

src/blog/templates/article_detail.html
{% extends "base.html"%}
{% load static %}
{% load disqus_tags %}
{% load i18n %}
{% disqus_dev %}

{% block title %}
{{article.title}}
{% endblock %}

{% block content %}
<div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-medium-3-4">
        <article class="uk-article">
            <h1 class="uk-article-title">
                <a href="{% url 'blog:article-detail' article.slug %}">{{article.title}}</a>
            </h1>
            <p class="uk-article-meta">Autor: {{article.author|capfirst}} | {{article.created}} Posted in <a href="#">Blog</a></p>
                <p>
                    <a href="{% url 'blog:article-detail' article.slug %}"><img src="{{get_media_prefix}}{{article.img}}" alt=""></a>
                </p>
                <p>{{article.short_description}}</p>
                <p>
                    <a class="uk-button uk-button-primary" href="{% url 'blog:article-detail' article.slug %}">Continue Reading</a>
                </p>
            {% disqus_show_comments %}
        </article>
    </div>

</div>

{% endblock %}

src/blog/templates/article_list.html
{% extends "base.html"%}

{% load static %}
{% load i18n %}

{% block content %}
<div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-medium-3-4">
    {% for article in articles %}
    {% if article.published %}
        <article class="uk-article">
            <h1 class="uk-article-title">
                <a href="{% url 'blog:article-detail' article.slug %}">{{article.title}}</a>
            </h1>
            <p class="uk-article-meta">Autor: {{article.author|capfirst}} | {{article.created}}{% if article.category %} {% trans "Posted in" %} <a href="{% url 'blog:category-list' article.category %}">{{article.category|capfirst}}</a>{% endif %}</p>
            <div class="uk-grid">
            <div class="uk-width-1-6">
                <p>
                    <a href="{% url 'blog:article-detail' article.slug %}"><img width="300" height="300" src="{% get_media_prefix %}{{article.img.small}}"
                                                                           alt="{{article.title}}"></a>
                </p>
            </div>
            <div class="uk-width-5-6">
                <p>{{article.short_description}}</p>
            </div>
        </div>
        </article>
    {% endif %}
    {% endfor %}

        <ul class="uk-pagination">
            <li class="uk-disabled"><span><i class="uk-icon-angle-double-left"></i></span></li>
            <li class="uk-active"><span>1</span></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><span>...</span></li>
            <li><a href="#">20</a></li>
            <li><a href="#"><i class="uk-icon-angle-double-right"></i></a></li>
        </ul>

    </div>

    <div class="uk-width-medium-1-4">
        <div class="uk-panel">
            <h3 class="uk-panel-title">Archives</h3>
            <ul class="uk-list uk-list-line">
                <li><a href="#">January 2014</a></li>
                <li><a href="#">December 2013</a></li>
                <li><a href="#">November 2013</a></li>
                <li><a href="#">October 2013</a></li>
                <li><a href="#">September 2013</a></li>
            </ul>
        </div>
        <div class="uk-panel">
            <h3 class="uk-panel-title">Social Links</h3>
            <ul class="uk-list">
                <li><a href="#">GitHub</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

src/blog_cms/templates/base.html
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link href="{% static 'uikit/css/uikit.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body>
    <div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}
    </div>

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'uikit/js/uikit.min.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

src/blog_cms/templates/navbar.html
<nav class="uk-navbar uk-margin-large-bottom">
    <a class="uk-navbar-brand uk-hidden-small" href="{% url 'blog:article-list' %}">Blog</a>
    <ul class="uk-navbar-nav uk-hidden-small">
        <li>
            <a href="{% url 'blog:article-list' %}">Strona główna</a>
        </li>
        <li>
            <a href="#">O mnie</a>
    </ul>
    <a href="#offcanvas" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>
    <div class="uk-navbar-brand uk-navbar-center uk-visible-small">Blog</div>
</nav>

<div id="offcanvas" class="uk-offcanvas">
    <div class="uk-offcanvas-bar">
        <ul class="uk-navbar-nav uk-hidden-small">
            <li>
                <a href="{% url 'blog:article-list' %}">Strona główna</a>
            </li>
            <li>
                <a href="#">O mnie</a>
        </ul>
    </div>
</div>